### ISSUE TITLE
tlog - nbdserver : fix one connection one vdisk assumption.

### ISSUE THREAD

**Issue by iwanbk** [g8os/blockstor#129]
tlog server assumed one client connection can only used by one vdisk.
While the nbdserver expect that one client can be used by more than one vdisks.

**Comment by iwanbk** [comment]
thanks to @GlenDC  for catching this issue at https://github.com/g8os/blockstor/pull/127#discussion_r115394781.

We can blame `tlogclient.Send` author (me) that provide `vdiskID` argument on each call.

Performance wise, with single connections for all vdisk, only one CPU core of tlog that will receive the packet. It is the case with dpdk, seastar, and Nim. And i think is the same for Go, at least in the in network stack level.

We have many alternatives:
- change nbdserver to only have one vdisk on a single connection -> it is my preference from tlog point of view, perfect choice, not sure how it will affect nbdserver code
- nbdserver create many connections, each connection can have many vdisk ID -> it is also OK for tlog.
- single connection for many vdisks -> it is current implementation in nbd, the worst i think

**Comment by GlenDC** [comment]
> single connection for many vdisks -> it is current implementation in nbd, the worst i think

No that's not true. The tlogclient instance is created in the nbdserver in the backend object, which is a per-vdisk object. Thus the tlogclient as used in the nbdserver is only used for a single vdisk.

My comment on the linked issue #127, was about potential other places where the tlogclient might be used in the future (dunno if that will ever the case). And the fact that the server didn't seem to validate that possible scenario, which is a failure on the part of the server.

So I think you can simply keep your assumption that we have only 1 vdisk per tlog connection, but:

1. make sure that this assumption is documented;
2. validate that vdiskID on the server side, you never know;
3. update the tlogclient so that its constructor accepts a vdiskID, and don't require it for each Send command, as that vdiskID will always have to be the same anyhow;

**Comment by iwanbk** [comment]
```
update the tlogclient so that its constructor accepts a vdiskID, and don't require it for each Send command, as that vdiskID will always have to be the same anyhow;
```
done at 41dc2b67e4f7881aeebf03af5fad4926b55c2676
```
validate that vdiskID on the server side, you never know;
```
already done in the code review phase
```
make sure that this assumption is documented;
```
i think it is already clear after we fix the tlog client.
