### ISSUE TITLE
tlog : remove vdisk ID from TlogBlock's field

### ISSUE THREAD

**Issue by iwanbk** [g8os/blockstor#141]
We already have vdiskID in aggregation's field.
And all blocks in aggregation has same vdisk ID

**Comment by GlenDC** [comment]
As we only store the aggregation (collection of blocks) in the ardb, I think it's safe to just have the vdisk in the aggregation, and remove it from all blocks (as a block should in that case be all "unique" properties). As we would store a hash of each aggregation in the blockchain (rivine), we would already influence the hash enough by just having it as a field in the aggregation, so that makes this issue pretty straightforward to resolve.

I agree that we should remove vdisk ID from the TlogBlock's field.

@robvanmieghem is there a special reason why the vdiskID was put in the original scheme of the TlogBlock, or is there no special reason, and can we remove it as we plan to do, and _just_ keep it in the aggregation schema?
