### ISSUE TITLE
provide log.Errorf

### ISSUE THREAD

**Issue by iwanbk** [g8os/blockstor#145]
continuing the discussion at https://github.com/g8os/blockstor/pull/127#discussion_r115397148.

```
If an error can't be handled it is fatal
```
in stdlib fatal means logging the error and then os.Exit(1). We don't always want to exit in case of error.

In case of error, we have something to worry, so we might add hook that triggered when some error happens. For example to notify sysadmin.

I know the logger is on separate library, but there is no point to fix it there without being used here.

**Comment by GlenDC** [comment]
Looking back at this, I might be a bit too minimalistic with the current logging approach.

We could switch to [logrus](https://github.com/Sirupsen/logrus), as that's a very popular and well maintained library, but:

- it doesn't support logging the file where the log originates, and nor will it ever support it (see: https://github.com/sirupsen/logrus/issues/63), there are however work arounds (mentioned in the same issue, so we could I guess work around this issue);

If we use it I would probably want to wrap it in a common g8os/blockstor/log module though:

+ this way we could add the hooks we want by default;
+ we could define custom hooks in this package as well (if needed);
+ we could drop-in a work around, and support file+linenumber logging;
+ we could improve the API a bit, and remove stuff we don't want to support (such as logging warnings), and prevent all the pointer stuff (which logrus seems to be a fan off);
+ we need to be disciplined and only log errors when we really have to (for tech support help or whatever), otherwise the hooks are going to be spammed, thus ignored and thus removing the usefulness of this all;

What do you think @iwanbk? If that all sounds more or less fine to you, I'll integrate this (Peru) Saturday morning. It will be part of the blockstor repo, so will also make it much easier to change things around.

**Comment by GlenDC** [comment]
Was going for logrus, but man that library is really pretty fucked up. After messing around with it, and going through it, I decided to go for https://github.com/inconshreveable/log15 instead:

+ It's a much smaller library, but a lot better written.
+ They still support hooks (called handlers) and they do support logging file (and line number) out of the box.
+ Also the library has a much better API, which allows us in a much better way, to encapsulate it behind our own API, so we can later easily switch it out for another one.

**Comment by iwanbk** [comment]
> What do you think @iwanbk? If that all sounds more or less fine to you

Both logrus and log15 are fine for me

**Comment by GlenDC** [comment]
@iwanbk do you have any hooks that you want me to support already as well? Like did you have any services in mind to notify sys admins in case of error?

**Comment by iwanbk** [comment]
Nope.

**Comment by iwanbk** [comment]
I think the  logger package might not need to support hook feature because log monitor/processor can do this for us.

**Comment by GlenDC** [comment]
> I think the logger package might not need to support hook feature because log monitor/processor can do this for us.

Fair enough, it will support hooks anyhow (as this also allows to log to files, sysLog and email).

But you could still use log monitor/processor on top if for some reason that's required, but I don't think it would give any benefit.
