### ISSUE TITLE
tlogserver: get the ardb connectionstrings from a config.yml file

### ISSUE THREAD

**Issue by robvanmieghem** [g8os/blockstor#170]
Similar to the nbdserver, don't remove the commandline possibility though. If the storage-addresses parameter is present, it overrules the configfile.

**Comment by GlenDC** [comment]
@robvanmieghem I suppose you see this as a new config file format, separate from the nbdserver one?

**Comment by GlenDC** [comment]
After some reflection and discussions, here's what will happen in order to resolve this issue:

+ the tlog server will no longer require a server count equal to (`K+M+1`), and instead work using a storageCluster, in a similar fashion as the deduped vdisk gets its ardbs (thus using modulo indices);
+ the tlog server will still accept parameters to specify connection strings, if these connection strings have been passed via the CLI, the storageCluster version will not be used, and instead a hardcoded version is used;
+ the `github.com/g8os/blockstor/nbdserver/config` module will be moved to `github.com/g8os/blockstor/config` and its format will be adapted, to give the vdisk an extra optional property: `tlogStorageCluster: string`, which will be used by the tlogserver if found;
+ if no connectionstring(s) were given via the command line, and no config file can be found, the tlogserver will fail at startup with a non-`0` status code;

**Comment by iwanbk** [comment]
```
the tlog server will no longer require a server count equal to (K+M+1), and instead work using a storageCluster, in a similar fashion as the deduped vdisk gets its ardbs (thus using modulo indices);
```
If what you mean is we only need `less than K+M` ardb to store the erasure encoded pieces, then there is no point to use erasure encoding with that K & M values.

If we only have N ardb, then we can adjust K & M to be `K+M=N`

**Comment by GlenDC** [comment]
I have moved the config module already, and is now available at `github.com/g8os/blockstor/config` since master commit: https://github.com/g8os/blockstor/commit/fe61906e396b06ae8ca14dfdfe7045ba2aaf6aca

That commit also prepares the config to be fully ready to have a `tlogStorageCluster` specified for vdisks.

**Comment by GlenDC** [comment]
Sorry @iwanbk, I totally looked over the requirement that we need to ensure a certain amount of storage servers (`K+M`). Will edit my original comment to reflect that.

**Comment by GlenDC** [comment]
I pushed my current WIP code (and its direction) to https://github.com/g8os/blockstor/tree/tlog-config, you can find the wip code as the commit: https://github.com/g8os/blockstor/commit/fee74598523bf56cab66e498d5dffab1d046bef2

**Comment by GlenDC** [comment]
Will take a fresh look at this tomorrow, probably with a fresh, waaay simpler design. After talking with @iwanbk, I think I misinterpreted this issue quite a lot. And implemented features that probably aren't required yet, making this way more complicated then they have to be.
