### ISSUE TITLE
Deduped volumes do not work with the inmemory storage option

### ISSUE THREAD

**Issue by robvanmieghem** [g8os/blockstor#41]
The LBAstructure now uses the `HSET` and `HGET` commands which are not implemented in the redis stub

**Comment by robvanmieghem** [comment]
https://github.com/g8os/blockstor/commit/c7b507c45aef1afce739d2188123b4eb6319baf5

**Comment by GlenDC** [comment]
You probably do want to implement `MULTI` and `EXEC`. The reason why it works (or at least I hope it actually works) is that you would only see it go wrong in case an error happened. As a transaction block, (starts with `MULTI`, ends with `EXEC`), ensures that either all commands succeed, or none of them. The other benefits is that it sends and executes everything in 1 go. That last benefit however is not really important for the inMemory version. But yeah, I would definitely implement it if I was yours, otherwise the inMemory might execute partial blocks in case of errors, which would be deviating from the actual redis behavior, making the stub less then ideal.

Besides this remark and my comments, it looks pretty good. Very cool! I'm always afraid about stubs though, as they always make me thing that some behavior might be different than the actual client. I wonder if we shouldn't perhaps add a performant stub (inMemory) client to the redigo library as a contribution, this would at least give it a lot more reviews to ensure that the behavior matches an actual client. Than again, we might not have time for any of this.

**Comment by robvanmieghem** [comment]
It seems to work because of an error during a flush command is not propagated:
https://github.com/g8os/blockstor/issues/43
